# ---------------------------------------------------------------------------
# export.py
# Created on: 周二 一月 15 2013 11:42:41 上午
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()

# Load required toolboxes...
gp.AddToolbox("D:/Program Files (x86)/ArcGIS/ArcToolbox/Toolboxes/Analysis Tools.tbx")


# Local variables...
道路中心线 = "E:\\广州城市地图综合\\验收\\演示数据\\道路数据.gdb\\道路中心线"
裁切区域 = "裁切区域"
SDE_DEFAULT道路中心线全部 = "SDE.DEFAULT道路中心线全部"

# Process: Clip...
gp.Clip_analysis(SDE_DEFAULT道路中心线全部, 裁切区域, 道路中心线, "")

